spring:
  profiles:
    active: dev

mybatis:
  #mapper.xml所在的位置
  mapper-locations: classpath*:mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true