server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://112.74.185.224:3306/xiaoqi?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: xiaoqi
    password: Xiaoqi2022.
    driver-class-name: com.mysql.cj.jdbc.Driver