package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.AbstractPo;
import top.beforedawn.service.model.po.AbstractPoExample;

public interface AbstractPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int insert(AbstractPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int insertSelective(AbstractPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    List<AbstractPo> selectByExample(AbstractPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    AbstractPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AbstractPo record, @Param("example") AbstractPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AbstractPo record, @Param("example") AbstractPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AbstractPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abstract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AbstractPo record);
}