package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.AuthorizationPo;
import top.beforedawn.service.model.po.AuthorizationPoExample;

public interface AuthorizationPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int insert(AuthorizationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int insertSelective(AuthorizationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    List<AuthorizationPo> selectByExample(AuthorizationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    AuthorizationPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthorizationPo record, @Param("example") AuthorizationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthorizationPo record, @Param("example") AuthorizationPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthorizationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthorizationPo record);
}