package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.BotPo;
import top.beforedawn.service.model.po.BotPoExample;

public interface BotPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int insert(BotPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int insertSelective(BotPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    List<BotPo> selectByExample(BotPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    BotPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BotPo record, @Param("example") BotPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BotPo record, @Param("example") BotPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BotPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BotPo record);
}