package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.DriftingBottlePo;
import top.beforedawn.service.model.po.DriftingBottlePoExample;

public interface DriftingBottlePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int insert(DriftingBottlePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int insertSelective(DriftingBottlePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    List<DriftingBottlePo> selectByExample(DriftingBottlePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    DriftingBottlePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DriftingBottlePo record, @Param("example") DriftingBottlePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DriftingBottlePo record, @Param("example") DriftingBottlePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DriftingBottlePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drifting_bottle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DriftingBottlePo record);
}