package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.FortunePo;
import top.beforedawn.service.model.po.FortunePoExample;

public interface FortunePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int insert(FortunePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int insertSelective(FortunePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    List<FortunePo> selectByExample(FortunePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    FortunePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FortunePo record, @Param("example") FortunePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FortunePo record, @Param("example") FortunePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FortunePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fortune
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FortunePo record);
}