package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.IdiomPo;
import top.beforedawn.service.model.po.IdiomPoExample;

public interface IdiomPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int insert(IdiomPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int insertSelective(IdiomPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    List<IdiomPo> selectByExample(IdiomPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    IdiomPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IdiomPo record, @Param("example") IdiomPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IdiomPo record, @Param("example") IdiomPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IdiomPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IdiomPo record);
}