package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.KeyPo;
import top.beforedawn.service.model.po.KeyPoExample;

public interface KeyPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int insert(KeyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int insertSelective(KeyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    List<KeyPo> selectByExample(KeyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    KeyPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KeyPo record, @Param("example") KeyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KeyPo record, @Param("example") KeyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KeyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KeyPo record);
}