package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.QuestionsAnswersPo;
import top.beforedawn.service.model.po.QuestionsAnswersPoExample;

public interface QuestionsAnswersPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int insert(QuestionsAnswersPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int insertSelective(QuestionsAnswersPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    List<QuestionsAnswersPo> selectByExample(QuestionsAnswersPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    QuestionsAnswersPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestionsAnswersPo record, @Param("example") QuestionsAnswersPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestionsAnswersPo record, @Param("example") QuestionsAnswersPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestionsAnswersPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions_answers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionsAnswersPo record);
}