package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.RiddlePo;
import top.beforedawn.service.model.po.RiddlePoExample;

public interface RiddlePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int insert(RiddlePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int insertSelective(RiddlePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    List<RiddlePo> selectByExample(RiddlePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    RiddlePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RiddlePo record, @Param("example") RiddlePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RiddlePo record, @Param("example") RiddlePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RiddlePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table riddle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RiddlePo record);
}