package top.beforedawn.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.beforedawn.service.model.po.VocabularyPo;
import top.beforedawn.service.model.po.VocabularyPoExample;

public interface VocabularyPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int insert(VocabularyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int insertSelective(VocabularyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    List<VocabularyPo> selectByExample(VocabularyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    VocabularyPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VocabularyPo record, @Param("example") VocabularyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VocabularyPo record, @Param("example") VocabularyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VocabularyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vocabulary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VocabularyPo record);
}