package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class AuthorizationPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.valid_begin_date
     *
     * @mbg.generated
     */
    private LocalDateTime validBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.valid_end_date
     *
     * @mbg.generated
     */
    private LocalDateTime validEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorization.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.id
     *
     * @return the value of authorization.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.id
     *
     * @param id the value for authorization.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.value
     *
     * @return the value of authorization.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.value
     *
     * @param value the value for authorization.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.user_id
     *
     * @return the value of authorization.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.user_id
     *
     * @param userId the value for authorization.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.valid_begin_date
     *
     * @return the value of authorization.valid_begin_date
     *
     * @mbg.generated
     */
    public LocalDateTime getValidBeginDate() {
        return validBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.valid_begin_date
     *
     * @param validBeginDate the value for authorization.valid_begin_date
     *
     * @mbg.generated
     */
    public void setValidBeginDate(LocalDateTime validBeginDate) {
        this.validBeginDate = validBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.valid_end_date
     *
     * @return the value of authorization.valid_end_date
     *
     * @mbg.generated
     */
    public LocalDateTime getValidEndDate() {
        return validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.valid_end_date
     *
     * @param validEndDate the value for authorization.valid_end_date
     *
     * @mbg.generated
     */
    public void setValidEndDate(LocalDateTime validEndDate) {
        this.validEndDate = validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.type
     *
     * @return the value of authorization.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.type
     *
     * @param type the value for authorization.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.modified
     *
     * @return the value of authorization.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.modified
     *
     * @param modified the value for authorization.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.modified_id
     *
     * @return the value of authorization.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.modified_id
     *
     * @param modifiedId the value for authorization.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.create
     *
     * @return the value of authorization.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.create
     *
     * @param create the value for authorization.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorization.create_id
     *
     * @return the value of authorization.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorization.create_id
     *
     * @param createId the value for authorization.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}