package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class BlacklistPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.key
     *
     * @mbg.generated
     */
    private Long key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.remind
     *
     * @mbg.generated
     */
    private Long remind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.last_remind_time
     *
     * @mbg.generated
     */
    private LocalDateTime lastRemindTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.id
     *
     * @return the value of blacklist.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.id
     *
     * @param id the value for blacklist.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.key
     *
     * @return the value of blacklist.key
     *
     * @mbg.generated
     */
    public Long getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.key
     *
     * @param key the value for blacklist.key
     *
     * @mbg.generated
     */
    public void setKey(Long key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.type
     *
     * @return the value of blacklist.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.type
     *
     * @param type the value for blacklist.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.comment
     *
     * @return the value of blacklist.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.comment
     *
     * @param comment the value for blacklist.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.remind
     *
     * @return the value of blacklist.remind
     *
     * @mbg.generated
     */
    public Long getRemind() {
        return remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.remind
     *
     * @param remind the value for blacklist.remind
     *
     * @mbg.generated
     */
    public void setRemind(Long remind) {
        this.remind = remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.last_remind_time
     *
     * @return the value of blacklist.last_remind_time
     *
     * @mbg.generated
     */
    public LocalDateTime getLastRemindTime() {
        return lastRemindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.last_remind_time
     *
     * @param lastRemindTime the value for blacklist.last_remind_time
     *
     * @mbg.generated
     */
    public void setLastRemindTime(LocalDateTime lastRemindTime) {
        this.lastRemindTime = lastRemindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.valid
     *
     * @return the value of blacklist.valid
     *
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.valid
     *
     * @param valid the value for blacklist.valid
     *
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.modified
     *
     * @return the value of blacklist.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.modified
     *
     * @param modified the value for blacklist.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.modified_id
     *
     * @return the value of blacklist.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.modified_id
     *
     * @param modifiedId the value for blacklist.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.create
     *
     * @return the value of blacklist.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.create
     *
     * @param create the value for blacklist.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.create_id
     *
     * @return the value of blacklist.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.create_id
     *
     * @param createId the value for blacklist.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}