package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class BotPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.qq
     *
     * @mbg.generated
     */
    private Long qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.master_qq
     *
     * @mbg.generated
     */
    private Long masterQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.key_id
     *
     * @mbg.generated
     */
    private Long keyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.allow_friend
     *
     * @mbg.generated
     */
    private Integer allowFriend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.allow_group
     *
     * @mbg.generated
     */
    private Integer allowGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.heart
     *
     * @mbg.generated
     */
    private Integer heart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.heart_interval
     *
     * @mbg.generated
     */
    private Integer heartInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.remind_friend
     *
     * @mbg.generated
     */
    private Integer remindFriend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.remind_group
     *
     * @mbg.generated
     */
    private Integer remindGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.remind_mute
     *
     * @mbg.generated
     */
    private Integer remindMute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.remind_quit
     *
     * @mbg.generated
     */
    private Integer remindQuit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.clear_blacklist
     *
     * @mbg.generated
     */
    private Integer clearBlacklist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.id
     *
     * @return the value of bot.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.id
     *
     * @param id the value for bot.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.qq
     *
     * @return the value of bot.qq
     *
     * @mbg.generated
     */
    public Long getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.qq
     *
     * @param qq the value for bot.qq
     *
     * @mbg.generated
     */
    public void setQq(Long qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.password
     *
     * @return the value of bot.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.password
     *
     * @param password the value for bot.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.name
     *
     * @return the value of bot.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.name
     *
     * @param name the value for bot.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.master_qq
     *
     * @return the value of bot.master_qq
     *
     * @mbg.generated
     */
    public Long getMasterQq() {
        return masterQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.master_qq
     *
     * @param masterQq the value for bot.master_qq
     *
     * @mbg.generated
     */
    public void setMasterQq(Long masterQq) {
        this.masterQq = masterQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.key_id
     *
     * @return the value of bot.key_id
     *
     * @mbg.generated
     */
    public Long getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.key_id
     *
     * @param keyId the value for bot.key_id
     *
     * @mbg.generated
     */
    public void setKeyId(Long keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.allow_friend
     *
     * @return the value of bot.allow_friend
     *
     * @mbg.generated
     */
    public Integer getAllowFriend() {
        return allowFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.allow_friend
     *
     * @param allowFriend the value for bot.allow_friend
     *
     * @mbg.generated
     */
    public void setAllowFriend(Integer allowFriend) {
        this.allowFriend = allowFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.allow_group
     *
     * @return the value of bot.allow_group
     *
     * @mbg.generated
     */
    public Integer getAllowGroup() {
        return allowGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.allow_group
     *
     * @param allowGroup the value for bot.allow_group
     *
     * @mbg.generated
     */
    public void setAllowGroup(Integer allowGroup) {
        this.allowGroup = allowGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.heart
     *
     * @return the value of bot.heart
     *
     * @mbg.generated
     */
    public Integer getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.heart
     *
     * @param heart the value for bot.heart
     *
     * @mbg.generated
     */
    public void setHeart(Integer heart) {
        this.heart = heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.heart_interval
     *
     * @return the value of bot.heart_interval
     *
     * @mbg.generated
     */
    public Integer getHeartInterval() {
        return heartInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.heart_interval
     *
     * @param heartInterval the value for bot.heart_interval
     *
     * @mbg.generated
     */
    public void setHeartInterval(Integer heartInterval) {
        this.heartInterval = heartInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.remind_friend
     *
     * @return the value of bot.remind_friend
     *
     * @mbg.generated
     */
    public Integer getRemindFriend() {
        return remindFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.remind_friend
     *
     * @param remindFriend the value for bot.remind_friend
     *
     * @mbg.generated
     */
    public void setRemindFriend(Integer remindFriend) {
        this.remindFriend = remindFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.remind_group
     *
     * @return the value of bot.remind_group
     *
     * @mbg.generated
     */
    public Integer getRemindGroup() {
        return remindGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.remind_group
     *
     * @param remindGroup the value for bot.remind_group
     *
     * @mbg.generated
     */
    public void setRemindGroup(Integer remindGroup) {
        this.remindGroup = remindGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.remind_mute
     *
     * @return the value of bot.remind_mute
     *
     * @mbg.generated
     */
    public Integer getRemindMute() {
        return remindMute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.remind_mute
     *
     * @param remindMute the value for bot.remind_mute
     *
     * @mbg.generated
     */
    public void setRemindMute(Integer remindMute) {
        this.remindMute = remindMute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.remind_quit
     *
     * @return the value of bot.remind_quit
     *
     * @mbg.generated
     */
    public Integer getRemindQuit() {
        return remindQuit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.remind_quit
     *
     * @param remindQuit the value for bot.remind_quit
     *
     * @mbg.generated
     */
    public void setRemindQuit(Integer remindQuit) {
        this.remindQuit = remindQuit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.clear_blacklist
     *
     * @return the value of bot.clear_blacklist
     *
     * @mbg.generated
     */
    public Integer getClearBlacklist() {
        return clearBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.clear_blacklist
     *
     * @param clearBlacklist the value for bot.clear_blacklist
     *
     * @mbg.generated
     */
    public void setClearBlacklist(Integer clearBlacklist) {
        this.clearBlacklist = clearBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.modified
     *
     * @return the value of bot.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.modified
     *
     * @param modified the value for bot.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.modified_id
     *
     * @return the value of bot.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.modified_id
     *
     * @param modifiedId the value for bot.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.create
     *
     * @return the value of bot.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.create
     *
     * @param create the value for bot.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot.create_id
     *
     * @return the value of bot.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot.create_id
     *
     * @param createId the value for bot.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}