package top.beforedawn.service.model.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class BotPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public BotPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("`qq` is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("`qq` is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(Long value) {
            addCriterion("`qq` =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(Long value) {
            addCriterion("`qq` <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(Long value) {
            addCriterion("`qq` >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(Long value) {
            addCriterion("`qq` >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(Long value) {
            addCriterion("`qq` <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(Long value) {
            addCriterion("`qq` <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<Long> values) {
            addCriterion("`qq` in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<Long> values) {
            addCriterion("`qq` not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(Long value1, Long value2) {
            addCriterion("`qq` between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(Long value1, Long value2) {
            addCriterion("`qq` not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("`password` is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("`password` is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("`password` =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("`password` <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("`password` >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("`password` >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("`password` <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("`password` <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("`password` like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("`password` not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("`password` in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("`password` not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("`password` between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("`password` not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMasterQqIsNull() {
            addCriterion("`master_qq` is null");
            return (Criteria) this;
        }

        public Criteria andMasterQqIsNotNull() {
            addCriterion("`master_qq` is not null");
            return (Criteria) this;
        }

        public Criteria andMasterQqEqualTo(Long value) {
            addCriterion("`master_qq` =", value, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqNotEqualTo(Long value) {
            addCriterion("`master_qq` <>", value, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqGreaterThan(Long value) {
            addCriterion("`master_qq` >", value, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqGreaterThanOrEqualTo(Long value) {
            addCriterion("`master_qq` >=", value, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqLessThan(Long value) {
            addCriterion("`master_qq` <", value, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqLessThanOrEqualTo(Long value) {
            addCriterion("`master_qq` <=", value, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqIn(List<Long> values) {
            addCriterion("`master_qq` in", values, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqNotIn(List<Long> values) {
            addCriterion("`master_qq` not in", values, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqBetween(Long value1, Long value2) {
            addCriterion("`master_qq` between", value1, value2, "masterQq");
            return (Criteria) this;
        }

        public Criteria andMasterQqNotBetween(Long value1, Long value2) {
            addCriterion("`master_qq` not between", value1, value2, "masterQq");
            return (Criteria) this;
        }

        public Criteria andKeyIdIsNull() {
            addCriterion("`key_id` is null");
            return (Criteria) this;
        }

        public Criteria andKeyIdIsNotNull() {
            addCriterion("`key_id` is not null");
            return (Criteria) this;
        }

        public Criteria andKeyIdEqualTo(Long value) {
            addCriterion("`key_id` =", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotEqualTo(Long value) {
            addCriterion("`key_id` <>", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdGreaterThan(Long value) {
            addCriterion("`key_id` >", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`key_id` >=", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdLessThan(Long value) {
            addCriterion("`key_id` <", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdLessThanOrEqualTo(Long value) {
            addCriterion("`key_id` <=", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdIn(List<Long> values) {
            addCriterion("`key_id` in", values, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotIn(List<Long> values) {
            addCriterion("`key_id` not in", values, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdBetween(Long value1, Long value2) {
            addCriterion("`key_id` between", value1, value2, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotBetween(Long value1, Long value2) {
            addCriterion("`key_id` not between", value1, value2, "keyId");
            return (Criteria) this;
        }

        public Criteria andAllowFriendIsNull() {
            addCriterion("`allow_friend` is null");
            return (Criteria) this;
        }

        public Criteria andAllowFriendIsNotNull() {
            addCriterion("`allow_friend` is not null");
            return (Criteria) this;
        }

        public Criteria andAllowFriendEqualTo(Integer value) {
            addCriterion("`allow_friend` =", value, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendNotEqualTo(Integer value) {
            addCriterion("`allow_friend` <>", value, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendGreaterThan(Integer value) {
            addCriterion("`allow_friend` >", value, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendGreaterThanOrEqualTo(Integer value) {
            addCriterion("`allow_friend` >=", value, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendLessThan(Integer value) {
            addCriterion("`allow_friend` <", value, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendLessThanOrEqualTo(Integer value) {
            addCriterion("`allow_friend` <=", value, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendIn(List<Integer> values) {
            addCriterion("`allow_friend` in", values, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendNotIn(List<Integer> values) {
            addCriterion("`allow_friend` not in", values, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendBetween(Integer value1, Integer value2) {
            addCriterion("`allow_friend` between", value1, value2, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowFriendNotBetween(Integer value1, Integer value2) {
            addCriterion("`allow_friend` not between", value1, value2, "allowFriend");
            return (Criteria) this;
        }

        public Criteria andAllowGroupIsNull() {
            addCriterion("`allow_group` is null");
            return (Criteria) this;
        }

        public Criteria andAllowGroupIsNotNull() {
            addCriterion("`allow_group` is not null");
            return (Criteria) this;
        }

        public Criteria andAllowGroupEqualTo(Integer value) {
            addCriterion("`allow_group` =", value, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupNotEqualTo(Integer value) {
            addCriterion("`allow_group` <>", value, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupGreaterThan(Integer value) {
            addCriterion("`allow_group` >", value, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("`allow_group` >=", value, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupLessThan(Integer value) {
            addCriterion("`allow_group` <", value, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupLessThanOrEqualTo(Integer value) {
            addCriterion("`allow_group` <=", value, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupIn(List<Integer> values) {
            addCriterion("`allow_group` in", values, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupNotIn(List<Integer> values) {
            addCriterion("`allow_group` not in", values, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupBetween(Integer value1, Integer value2) {
            addCriterion("`allow_group` between", value1, value2, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andAllowGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("`allow_group` not between", value1, value2, "allowGroup");
            return (Criteria) this;
        }

        public Criteria andHeartIsNull() {
            addCriterion("`heart` is null");
            return (Criteria) this;
        }

        public Criteria andHeartIsNotNull() {
            addCriterion("`heart` is not null");
            return (Criteria) this;
        }

        public Criteria andHeartEqualTo(Integer value) {
            addCriterion("`heart` =", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotEqualTo(Integer value) {
            addCriterion("`heart` <>", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartGreaterThan(Integer value) {
            addCriterion("`heart` >", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartGreaterThanOrEqualTo(Integer value) {
            addCriterion("`heart` >=", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartLessThan(Integer value) {
            addCriterion("`heart` <", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartLessThanOrEqualTo(Integer value) {
            addCriterion("`heart` <=", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartIn(List<Integer> values) {
            addCriterion("`heart` in", values, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotIn(List<Integer> values) {
            addCriterion("`heart` not in", values, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartBetween(Integer value1, Integer value2) {
            addCriterion("`heart` between", value1, value2, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotBetween(Integer value1, Integer value2) {
            addCriterion("`heart` not between", value1, value2, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalIsNull() {
            addCriterion("`heart_interval` is null");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalIsNotNull() {
            addCriterion("`heart_interval` is not null");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalEqualTo(Integer value) {
            addCriterion("`heart_interval` =", value, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalNotEqualTo(Integer value) {
            addCriterion("`heart_interval` <>", value, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalGreaterThan(Integer value) {
            addCriterion("`heart_interval` >", value, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`heart_interval` >=", value, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalLessThan(Integer value) {
            addCriterion("`heart_interval` <", value, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("`heart_interval` <=", value, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalIn(List<Integer> values) {
            addCriterion("`heart_interval` in", values, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalNotIn(List<Integer> values) {
            addCriterion("`heart_interval` not in", values, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalBetween(Integer value1, Integer value2) {
            addCriterion("`heart_interval` between", value1, value2, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andHeartIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("`heart_interval` not between", value1, value2, "heartInterval");
            return (Criteria) this;
        }

        public Criteria andRemindFriendIsNull() {
            addCriterion("`remind_friend` is null");
            return (Criteria) this;
        }

        public Criteria andRemindFriendIsNotNull() {
            addCriterion("`remind_friend` is not null");
            return (Criteria) this;
        }

        public Criteria andRemindFriendEqualTo(Integer value) {
            addCriterion("`remind_friend` =", value, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendNotEqualTo(Integer value) {
            addCriterion("`remind_friend` <>", value, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendGreaterThan(Integer value) {
            addCriterion("`remind_friend` >", value, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendGreaterThanOrEqualTo(Integer value) {
            addCriterion("`remind_friend` >=", value, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendLessThan(Integer value) {
            addCriterion("`remind_friend` <", value, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendLessThanOrEqualTo(Integer value) {
            addCriterion("`remind_friend` <=", value, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendIn(List<Integer> values) {
            addCriterion("`remind_friend` in", values, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendNotIn(List<Integer> values) {
            addCriterion("`remind_friend` not in", values, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendBetween(Integer value1, Integer value2) {
            addCriterion("`remind_friend` between", value1, value2, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindFriendNotBetween(Integer value1, Integer value2) {
            addCriterion("`remind_friend` not between", value1, value2, "remindFriend");
            return (Criteria) this;
        }

        public Criteria andRemindGroupIsNull() {
            addCriterion("`remind_group` is null");
            return (Criteria) this;
        }

        public Criteria andRemindGroupIsNotNull() {
            addCriterion("`remind_group` is not null");
            return (Criteria) this;
        }

        public Criteria andRemindGroupEqualTo(Integer value) {
            addCriterion("`remind_group` =", value, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupNotEqualTo(Integer value) {
            addCriterion("`remind_group` <>", value, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupGreaterThan(Integer value) {
            addCriterion("`remind_group` >", value, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("`remind_group` >=", value, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupLessThan(Integer value) {
            addCriterion("`remind_group` <", value, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupLessThanOrEqualTo(Integer value) {
            addCriterion("`remind_group` <=", value, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupIn(List<Integer> values) {
            addCriterion("`remind_group` in", values, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupNotIn(List<Integer> values) {
            addCriterion("`remind_group` not in", values, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupBetween(Integer value1, Integer value2) {
            addCriterion("`remind_group` between", value1, value2, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("`remind_group` not between", value1, value2, "remindGroup");
            return (Criteria) this;
        }

        public Criteria andRemindMuteIsNull() {
            addCriterion("`remind_mute` is null");
            return (Criteria) this;
        }

        public Criteria andRemindMuteIsNotNull() {
            addCriterion("`remind_mute` is not null");
            return (Criteria) this;
        }

        public Criteria andRemindMuteEqualTo(Integer value) {
            addCriterion("`remind_mute` =", value, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteNotEqualTo(Integer value) {
            addCriterion("`remind_mute` <>", value, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteGreaterThan(Integer value) {
            addCriterion("`remind_mute` >", value, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("`remind_mute` >=", value, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteLessThan(Integer value) {
            addCriterion("`remind_mute` <", value, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteLessThanOrEqualTo(Integer value) {
            addCriterion("`remind_mute` <=", value, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteIn(List<Integer> values) {
            addCriterion("`remind_mute` in", values, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteNotIn(List<Integer> values) {
            addCriterion("`remind_mute` not in", values, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteBetween(Integer value1, Integer value2) {
            addCriterion("`remind_mute` between", value1, value2, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindMuteNotBetween(Integer value1, Integer value2) {
            addCriterion("`remind_mute` not between", value1, value2, "remindMute");
            return (Criteria) this;
        }

        public Criteria andRemindQuitIsNull() {
            addCriterion("`remind_quit` is null");
            return (Criteria) this;
        }

        public Criteria andRemindQuitIsNotNull() {
            addCriterion("`remind_quit` is not null");
            return (Criteria) this;
        }

        public Criteria andRemindQuitEqualTo(Integer value) {
            addCriterion("`remind_quit` =", value, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitNotEqualTo(Integer value) {
            addCriterion("`remind_quit` <>", value, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitGreaterThan(Integer value) {
            addCriterion("`remind_quit` >", value, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitGreaterThanOrEqualTo(Integer value) {
            addCriterion("`remind_quit` >=", value, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitLessThan(Integer value) {
            addCriterion("`remind_quit` <", value, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitLessThanOrEqualTo(Integer value) {
            addCriterion("`remind_quit` <=", value, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitIn(List<Integer> values) {
            addCriterion("`remind_quit` in", values, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitNotIn(List<Integer> values) {
            addCriterion("`remind_quit` not in", values, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitBetween(Integer value1, Integer value2) {
            addCriterion("`remind_quit` between", value1, value2, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andRemindQuitNotBetween(Integer value1, Integer value2) {
            addCriterion("`remind_quit` not between", value1, value2, "remindQuit");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistIsNull() {
            addCriterion("`clear_blacklist` is null");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistIsNotNull() {
            addCriterion("`clear_blacklist` is not null");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistEqualTo(Integer value) {
            addCriterion("`clear_blacklist` =", value, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistNotEqualTo(Integer value) {
            addCriterion("`clear_blacklist` <>", value, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistGreaterThan(Integer value) {
            addCriterion("`clear_blacklist` >", value, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistGreaterThanOrEqualTo(Integer value) {
            addCriterion("`clear_blacklist` >=", value, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistLessThan(Integer value) {
            addCriterion("`clear_blacklist` <", value, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistLessThanOrEqualTo(Integer value) {
            addCriterion("`clear_blacklist` <=", value, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistIn(List<Integer> values) {
            addCriterion("`clear_blacklist` in", values, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistNotIn(List<Integer> values) {
            addCriterion("`clear_blacklist` not in", values, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistBetween(Integer value1, Integer value2) {
            addCriterion("`clear_blacklist` between", value1, value2, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andClearBlacklistNotBetween(Integer value1, Integer value2) {
            addCriterion("`clear_blacklist` not between", value1, value2, "clearBlacklist");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("`modified` is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("`modified` is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(LocalDateTime value) {
            addCriterion("`modified` =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(LocalDateTime value) {
            addCriterion("`modified` <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(LocalDateTime value) {
            addCriterion("`modified` >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`modified` >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(LocalDateTime value) {
            addCriterion("`modified` <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`modified` <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<LocalDateTime> values) {
            addCriterion("`modified` in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<LocalDateTime> values) {
            addCriterion("`modified` not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`modified` between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`modified` not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIdIsNull() {
            addCriterion("`modified_id` is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIdIsNotNull() {
            addCriterion("`modified_id` is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedIdEqualTo(Long value) {
            addCriterion("`modified_id` =", value, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdNotEqualTo(Long value) {
            addCriterion("`modified_id` <>", value, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdGreaterThan(Long value) {
            addCriterion("`modified_id` >", value, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`modified_id` >=", value, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdLessThan(Long value) {
            addCriterion("`modified_id` <", value, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdLessThanOrEqualTo(Long value) {
            addCriterion("`modified_id` <=", value, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdIn(List<Long> values) {
            addCriterion("`modified_id` in", values, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdNotIn(List<Long> values) {
            addCriterion("`modified_id` not in", values, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdBetween(Long value1, Long value2) {
            addCriterion("`modified_id` between", value1, value2, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andModifiedIdNotBetween(Long value1, Long value2) {
            addCriterion("`modified_id` not between", value1, value2, "modifiedId");
            return (Criteria) this;
        }

        public Criteria andCreateIsNull() {
            addCriterion("`create` is null");
            return (Criteria) this;
        }

        public Criteria andCreateIsNotNull() {
            addCriterion("`create` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateEqualTo(LocalDateTime value) {
            addCriterion("`create` =", value, "create");
            return (Criteria) this;
        }

        public Criteria andCreateNotEqualTo(LocalDateTime value) {
            addCriterion("`create` <>", value, "create");
            return (Criteria) this;
        }

        public Criteria andCreateGreaterThan(LocalDateTime value) {
            addCriterion("`create` >", value, "create");
            return (Criteria) this;
        }

        public Criteria andCreateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create` >=", value, "create");
            return (Criteria) this;
        }

        public Criteria andCreateLessThan(LocalDateTime value) {
            addCriterion("`create` <", value, "create");
            return (Criteria) this;
        }

        public Criteria andCreateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create` <=", value, "create");
            return (Criteria) this;
        }

        public Criteria andCreateIn(List<LocalDateTime> values) {
            addCriterion("`create` in", values, "create");
            return (Criteria) this;
        }

        public Criteria andCreateNotIn(List<LocalDateTime> values) {
            addCriterion("`create` not in", values, "create");
            return (Criteria) this;
        }

        public Criteria andCreateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create` between", value1, value2, "create");
            return (Criteria) this;
        }

        public Criteria andCreateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create` not between", value1, value2, "create");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("`create_id` is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("`create_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("`create_id` =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("`create_id` <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("`create_id` >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`create_id` >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("`create_id` <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("`create_id` <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("`create_id` in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("`create_id` not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("`create_id` between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("`create_id` not between", value1, value2, "createId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}