package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class DriftingBottlePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.permanment
     *
     * @mbg.generated
     */
    private Byte permanment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drifting_bottle.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.id
     *
     * @return the value of drifting_bottle.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.id
     *
     * @param id the value for drifting_bottle.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.text
     *
     * @return the value of drifting_bottle.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.text
     *
     * @param text the value for drifting_bottle.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.valid
     *
     * @return the value of drifting_bottle.valid
     *
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.valid
     *
     * @param valid the value for drifting_bottle.valid
     *
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.permanment
     *
     * @return the value of drifting_bottle.permanment
     *
     * @mbg.generated
     */
    public Byte getPermanment() {
        return permanment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.permanment
     *
     * @param permanment the value for drifting_bottle.permanment
     *
     * @mbg.generated
     */
    public void setPermanment(Byte permanment) {
        this.permanment = permanment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.modified
     *
     * @return the value of drifting_bottle.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.modified
     *
     * @param modified the value for drifting_bottle.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.modified_id
     *
     * @return the value of drifting_bottle.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.modified_id
     *
     * @param modifiedId the value for drifting_bottle.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.create
     *
     * @return the value of drifting_bottle.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.create
     *
     * @param create the value for drifting_bottle.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drifting_bottle.create_id
     *
     * @return the value of drifting_bottle.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drifting_bottle.create_id
     *
     * @param createId the value for drifting_bottle.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}