package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class FortunePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fortune.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fortune.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fortune.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fortune.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fortune.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fortune.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fortune.id
     *
     * @return the value of fortune.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fortune.id
     *
     * @param id the value for fortune.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fortune.text
     *
     * @return the value of fortune.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fortune.text
     *
     * @param text the value for fortune.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fortune.modified
     *
     * @return the value of fortune.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fortune.modified
     *
     * @param modified the value for fortune.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fortune.modified_id
     *
     * @return the value of fortune.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fortune.modified_id
     *
     * @param modifiedId the value for fortune.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fortune.create
     *
     * @return the value of fortune.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fortune.create
     *
     * @param create the value for fortune.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fortune.create_id
     *
     * @return the value of fortune.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fortune.create_id
     *
     * @param createId the value for fortune.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}