package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class KeyPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.valid_begin_date
     *
     * @mbg.generated
     */
    private LocalDateTime validBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.valid_end_date
     *
     * @mbg.generated
     */
    private LocalDateTime validEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.id
     *
     * @return the value of key.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.id
     *
     * @param id the value for key.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.key
     *
     * @return the value of key.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.key
     *
     * @param key the value for key.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.valid_begin_date
     *
     * @return the value of key.valid_begin_date
     *
     * @mbg.generated
     */
    public LocalDateTime getValidBeginDate() {
        return validBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.valid_begin_date
     *
     * @param validBeginDate the value for key.valid_begin_date
     *
     * @mbg.generated
     */
    public void setValidBeginDate(LocalDateTime validBeginDate) {
        this.validBeginDate = validBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.valid_end_date
     *
     * @return the value of key.valid_end_date
     *
     * @mbg.generated
     */
    public LocalDateTime getValidEndDate() {
        return validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.valid_end_date
     *
     * @param validEndDate the value for key.valid_end_date
     *
     * @mbg.generated
     */
    public void setValidEndDate(LocalDateTime validEndDate) {
        this.validEndDate = validEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.type
     *
     * @return the value of key.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.type
     *
     * @param type the value for key.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.modified
     *
     * @return the value of key.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.modified
     *
     * @param modified the value for key.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.modified_id
     *
     * @return the value of key.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.modified_id
     *
     * @param modifiedId the value for key.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.create
     *
     * @return the value of key.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.create
     *
     * @param create the value for key.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.create_id
     *
     * @return the value of key.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.create_id
     *
     * @param createId the value for key.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}