package top.beforedawn.service.model.po;

import java.time.LocalDateTime;

public class RiddlePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.anaswer
     *
     * @mbg.generated
     */
    private String anaswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.modified_id
     *
     * @mbg.generated
     */
    private Long modifiedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.create
     *
     * @mbg.generated
     */
    private LocalDateTime create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column riddle.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.id
     *
     * @return the value of riddle.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.id
     *
     * @param id the value for riddle.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.question
     *
     * @return the value of riddle.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.question
     *
     * @param question the value for riddle.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.anaswer
     *
     * @return the value of riddle.anaswer
     *
     * @mbg.generated
     */
    public String getAnaswer() {
        return anaswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.anaswer
     *
     * @param anaswer the value for riddle.anaswer
     *
     * @mbg.generated
     */
    public void setAnaswer(String anaswer) {
        this.anaswer = anaswer == null ? null : anaswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.modified
     *
     * @return the value of riddle.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.modified
     *
     * @param modified the value for riddle.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.modified_id
     *
     * @return the value of riddle.modified_id
     *
     * @mbg.generated
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.modified_id
     *
     * @param modifiedId the value for riddle.modified_id
     *
     * @mbg.generated
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.create
     *
     * @return the value of riddle.create
     *
     * @mbg.generated
     */
    public LocalDateTime getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.create
     *
     * @param create the value for riddle.create
     *
     * @mbg.generated
     */
    public void setCreate(LocalDateTime create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column riddle.create_id
     *
     * @return the value of riddle.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column riddle.create_id
     *
     * @param createId the value for riddle.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
}